site_url: https://berbl.github.io
site_name: BERBL
repo_url: https://github.com/berbl-dev/berbl
# TODO site_description

site_author: David Pätzel
copyright: © 2022 David Pätzel

nav:
  - 'index.md'
  - API: reference/

theme:
  # name: readthedocs
  name: material
  highlightjs: true
  palette:
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  # Link to any Markdown heading.
  - autorefs
  - search
  # See https://mkdocstrings.github.io/recipes/ .
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  # Insert doc strings.
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://mkdocstrings.github.io/objects.inv
          - https://mkdocstrings.github.io/griffe/objects.inv
          rendering:
            merge_init_into_class: yes
            show_submodules: no
          selection:
            docstring_style: numpy
      watch:
        - src/
